# Generated by Django 4.1.7 on 2023-03-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_orderitem_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="user",
            new_name="customer_name",
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="email",
            new_name="phone",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="name",
        ),
        migrations.AddField(
            model_name="customer",
            name="gender",
            field=models.BooleanField(default=True, null=True),
        ),
    ]
