# Generated by Django 4.1.7 on 2023-03-21 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_remove_customer_cid"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OrderItem",
            new_name="OrderHasProduct",
        ),
    ]
