# Generated by Django 4.1.7 on 2023-03-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_rename_digital_product_is_on_sale_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="complete",
            new_name="is_complete",
        ),
        migrations.RenameField(
            model_name="orderhasproduct",
            old_name="order",
            new_name="oid",
        ),
        migrations.RenameField(
            model_name="orderhasproduct",
            old_name="product",
            new_name="pid",
        ),
        migrations.RenameField(
            model_name="orderhasproduct",
            old_name="quantity",
            new_name="product_count",
        ),
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.FloatField(null=True),
        ),
    ]
