# Generated by Django 4.1.7 on 2023-03-21 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_rename_complete_order_is_complete_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="transaction_id",
        ),
    ]
