# Generated by Django 4.1.7 on 2023-03-21 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_remove_order_transaction_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="customer",
            new_name="cid",
        ),
    ]
