# Generated by Django 4.1.7 on 2023-03-21 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_rename_customer_order_cid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="cid",
            new_name="customer",
        ),
    ]
