# Generated by Django 4.1.7 on 2023-03-22 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_rename_cid_order_customer"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OrderHasProduct",
            new_name="OrderItem",
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.FloatField(default=0, null=True),
        ),
    ]
