# Generated by Django 4.1.7 on 2023-03-22 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_rename_orderhasproduct_orderitem_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="oid",
            new_name="order",
        ),
        migrations.RenameField(
            model_name="orderitem",
            old_name="pid",
            new_name="product",
        ),
    ]
